//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Reporting.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Permissions
    {
        public int PermissionID { get; set; }
        public string UserID { get; set; }
        public string Form { get; set; }
        public string Description { get; set; }
        public Nullable<bool> Viewer { get; set; }
        public Nullable<bool> Creater { get; set; }
        public Nullable<bool> Editer { get; set; }
        public Nullable<bool> Deleter { get; set; }
        public Nullable<bool> Printer { get; set; }
    }
}
